name: 🚀 Deploy Website to Sakura Rental Server

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 📂 Sync files via SFTP
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via SFTP
        uses: milanmk/actions-file-deployer@v1.18
        with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.SFTP_SERVER }}
          remote-port: 22
          remote-user: ${{ secrets.SFTP_USERNAME }}
          remote-password: ${{ secrets.SFTP_PASSWORD }}
          remote-path: "/home/kogaku-sha/www/"
          sync-delta-excludes: ".git/ .github/ node_modules/ wp-content/uploads/ wp-content/cache/ wp-content/backups/ README.md screenshot.png"

